### ISSUE TITLE
setup-workspace: ask user if a proxy is used and configure it in generator

### ISSUE THREAD

**Issue by lehnerchristian** [phovea/generator-phovea#119]
if the user wants to use a proxy the URL could be typed into a generator prompt and then injected into the Dockerfile

**Comment by sgratzl** [comment]
it should be sufficient to add `environment entries` within the generated docker-compose.yml file

**Comment by sgratzl** [comment]
I generalized the idea of patching the docker-compose and build scripts. 

a `docker-compose-patch.yaml` will be automatically included in the generated docker-compose yaml file and if needed in patch Dockerfiles, thus

```yaml
services:
  api:
    environment:
      - http_proxy=http://yourproxylocation
      - https_proxy=https://yourproxylocation
```

should to the trick without user intervention.
