### ISSUE TITLE
Add dependabot configuration

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#195]
We should add a dependabot configuration `.dependabot/config.yml` following the [documentation](https://dependabot.com/docs/config-file/#dependabot-config-files). Different configurations are necessary for each plugin type.

**Frontend plugins only**

```yml
version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    allowed_updates:
      - match:
          update_type: "security"
```

**Server plugins only**

```yml
version: 1
update_configs:
  # Keep requirements.txt up to date as soon as
  # new versions are published to the pip registry
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"

  # Keep Dockerfile up to date, batching pull requests weekly
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
```

@anita-steiner, @dg-datavisyn, @lehnerchristian Please check the suggested configurations (and the documentation). Are you fine with them? Otherwise we can also deactivate the bot somehow by playing around with [`ignored_updates`](https://dependabot.com/docs/config-file/#ignored_updates) and [`allowed_updates`](https://dependabot.com/docs/config-file/#allowed_updates).
