### ISSUE TITLE
Update CircleCI config to use workflows

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#196]
Currently the templates of `.circleci/config.yml` are not using the recommended workflow structure. We should update the config files accordingly. We can also introduce a nightly build trigger (which can be commented out).

```yml
version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: caleydo/phovea_circleci_python:v3.0
    steps:
      # ... depends on the plugin type ...
workflows:
  version: 2
#  build-nightly:
#    triggers:
#      - schedule:
#          cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#15_1_*_*_1-5 
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - build
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
```
